Follow upstream's dropping of the PatchSetAncestors table
Gerrit core dropped the PatchSetAncestors table in
4ebea5bd673fcfac8ccecb1fa30098a1ad71466f, which made compiling against
current master fail.

Error message is (re-formatted to fit the commit message):

[...]/ReplayRevisionsStep.java:133: error: cannot find symbol
        ChangeUtil.insertAncestors(db, ps.getId(), commit);
                  ^
  symbol:   method insertAncestors([...].ReviewDb,[...].PatchSet.Id,[...].RevCommit)
  location: class com.google.gerrit.server.ChangeUtil

So we stop filling the table when importing.

Bug: Issue 3637
Change-Id: Ic7546b31b87a8bd25094ec3ffb582259f043b0dd