Follow upstream's change of PatchSetInfoFactory's get method
Gerrit core changed the signature of PatchSetInfoFactory's get method
to additionally require a RevWalk [1], which made compiling against
current master fail [2]. Hence, we now pass the needed RevWalk to
again allow compilation against current master.

[1] Commit b9805aee6dfe73b79269f5f0915a79ae0709cf32
[2] See
http://builds.quelltextlich.at/gerrit/nightly/master/latest/importer.jar.build.stderr.txt
http://builds.quelltextlich.at/gerrit/nightly/master/latest/index.html#importer.jar

Error message is (re-formatted to fit the commit message):

[...]/ReplayRevisionsStep.java:128: error: no suitable method found
                          for get([...].RevCommit,[...].PatchSet.Id)
        info = patchSetInfoFactory.get(commit, ps.getId());
                                  ^

Bug: Issue 3615
Change-Id: Idf45020d6fdd3f8ad87d6e015c3e992c11c46291