Update patch set 1
Patch Set 1: Verified-1

Build fails for me:

/usr/local/google/home/ekempin/git/plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/HttpSession.java:77: error: no suitable constructor found for SSLConnectionSocketFactory(javax.net.ssl.SSLContext,com.googlesource.gerrit.plugins.importer.HttpSession.DummyHostnameVerifier)
      sf = new SSLConnectionSocketFactory(context, new DummyHostnameVerifier());
           ^
    constructor org.apache.http.conn.ssl.SSLConnectionSocketFactory.SSLConnectionSocketFactory(javax.net.ssl.SSLContext,org.apache.http.conn.ssl.X509HostnameVerifier) is not applicable
      (argument mismatch; com.googlesource.gerrit.plugins.importer.HttpSession.DummyHostnameVerifier cannot be converted to org.apache.http.conn.ssl.X509HostnameVerifier)
    constructor org.apache.http.conn.ssl.SSLConnectionSocketFactory.SSLConnectionSocketFactory(javax.net.ssl.SSLSocketFactory,org.apache.http.conn.ssl.X509HostnameVerifier) is not applicable
      (argument mismatch; javax.net.ssl.SSLContext cannot be converted to javax.net.ssl.SSLSocketFactory)
/usr/local/google/home/ekempin/git/plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ProjectsCollection.java:-1: note: Some input files use unchecked or unsafe operations.

/usr/local/google/home/ekempin/git/plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ProjectsCollection.java:-1: note: Recompile with -Xlint:unchecked for details.

: note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output

Errors: 1. Warnings: 1.

Patch-set: 1
Label: Verified=-1