Adapt to recent gerrit changes that broke compilation
The gerrit commits

  85f0487714e005b478eee5b28efab22bf5b7a5e2 (getCurrentUser -> User)
  bce0e922c429c819f30d1d8c86a8858bb661fa2a (Set Hashtag via BatchUpdate.Op)

broke the compilation of this plugin [1]. Hence, we follow gerrit's
changes to make it compile against latest master again.

[1] For example:
  [...]/AddHashtagsStep.java:76: error: cannot find symbol
          hashtagsUtil.setHashtags(ctrl, input, false, false);
                      ^
See

  http://builds.quelltextlich.at/gerrit/nightly/master/2015-10-20/importer.jar.build.stderr.txt

for full build log.

Bug: Issue 3622
Change-Id: Ie604b6e2beab8288274598a02ed59aa2557945b9