Update patch set 18
Patch Set 18:

new error

ERROR: /home/paladox/gerrit/plugins/importer/BUILD:3:1: Java compilation in rule '//plugins/importer:importer__plugin' failed: Worker process sent response with exit code: 1.
plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:198: error: incompatible types: PatchLineComment cannot be converted to Comment
      setCommentRevId(e, patchListCache, change, ps);
                      ^plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:214: error: incompatible types: List<PatchLineComment> cannot be converted to Iterable<Comment>
    plcUtil.deleteComments(db, update, del);
                                       ^plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:215: error: method putComments in class CommentsUtil cannot be applied to given types;
    plcUtil.putComments(db, update, ups);
           ^
  required: ReviewDb,ChangeUpdate,Status,Iterable<Comment>
  found: ReviewDb,ChangeUpdate,List<PatchLineComment>
  reason: actual and formal argument lists differ in lengthplugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:222: error: incompatible types: Comment cannot be converted to PatchLineComment
    for (PatchLineComment c : plcUtil.draftByPatchSetAuthor(db, ps.getId(),
                                                           ^Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full outputINFO: BuiTarget //plugins/importer:importer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.435s, Critical Path: 5.72s

Patch-set: 18
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0