Update patch set 17
Patch Set 17:

I get these errors

paladox@gerrit-test:~/gerrit$ bazel build plugins/importer
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/paladox/gerrit/plugins/importer/BUILD:3:1: Java compilation in rule '//plugins/importer:importer__plugin' failed: Worker process sent response with exit code: 1.
plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:76: error: cannot find symbol
  private final PatchLineCommentsUtil plcUtil;
                ^
  symbol:   class PatchLineCommentsUtil
  location: class ReplayInlineCommentsStepplugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/ReplayInlineCommentsStep.java:198: error: incompatible types: PatchLineComment cannot be converted to Comment
      setCommentRevId(e, patchListCache, change, ps);
                      ^plugins/importer/src/main/java/com/googlesource/gerrit/plugins/importer/InsertLinkToOriginalChangeStep.java:105: error: method messageUuid in class ChangeUtil cannot be applied to given types;
            ChangeUtil.messageUuid(db)), userId, TimeUtil.nowTs(),
                      ^
  required: no arguments
  found: ReviewDb
  reason: actual and formal argument lists differ in lengthNote: Some messages have been simplified; recompile with -Xdiags:verbose to get full outputTarget //plugins/importer:importer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.313s, Critical Path: 8.48s

@David Ostrovsky hi, any ideas on how i can fix this please?

Patch-set: 17
Label: Verified=0